### ISSUE TITLE
Moving functions from groceristar-fetch project GraphQL

### ISSUE THREAD

**Issue by vadim9999** [GroceriStar/sd#294] opened 2019-05-10 08:29 UTC
Here is a list of functions that should be moved and working without bugs. 
From https://github.com/GroceriStar/groceristar-fetch/blob/master/src/projects/GraphQL/graphQL.js need move to https://github.com/GroceriStar/sd/blob/master/generator/projects/GraphQL/graphQL this list of functions:

- [x] getUserGroceryKey (#302)
- [x] getIngredientsKey (#240)
- [x] getFavoritesKey (#303)
- [x] getItemsKey (#309)
- [x] getDepartmentsKey (#325 & #303)
- [x] getGroceryKey (#326)
- [x] getUsersKey (#327)

**Note**
---
Some methods for generating Id for each object in array using function __generateId(). 
For example in `getFavoritesKey()`  https://github.com/GroceriStar/groceristar-fetch/blob/master/src/projects/GraphQL/graphQL.js#L38 using `__generateId()` 
https://github.com/GroceriStar/groceristar-fetch/blob/master/src/projects/GraphQL/graphQL.js#L43
In this repository (SD) you can find `__generateId()` and `__generateDate` in https://github.com/GroceriStar/sd/blob/master/src/utils.js. 
When you will be importing `__generateId()` and `__generateDate()` use this 

```
const { __generateDate, __generateId } = require('../../../src/utils')
```

---
Uncomment test for the function that you have moved in graphQL.test.js https://github.com/GroceriStar/sd/tree/master/generator/projects/GraphQL/test

**Comment by atherdon** [comment] 2019-05-13 04:50
Can you put there what is needed to be done, please?

**Comment by atherdon** [comment] 2019-05-13 04:51
#240

**Comment by atherdon** [comment] 2019-05-15 23:22
if you can create a similar to this task, but related to groceristar methods - i think Eugene will be able to handle it himself quickly.

**Comment by atherdon** [comment] 2019-05-16 21:40
GraphQL functions
another important thing is how exactly you will did it.
For example: all is done with this part of functionality. And I decided to add two more files, that will extend the logic of our work.
How quickly you will be able to handle it?

1) we finished our changes at sd repository. tests of this part is working fine. Vadim confirmed it.
2) Vadim/Eugene publishing sd module at npm. Someone install it(an updated version)  at `groceristar-fetch`
and run tests there too.
3) all is working at `groceristar-fetch` fine, and Vadim/Eugene publishing that module at npm.
4) someone update module(`gs-fetch`) at groceristar-graphql-server repository[link]
and all tests there should work well.

How I can review the end result? It's simple.
I'll run a graphql server and check results of different queries to database.
if all works fine - then this task is closed.

**Comment by ijb87** [comment] 2019-05-17 23:15
https://github.com/GroceriStar/sd/blob/master/generator/projects/GraphQL/graphQL link isn't working

**Comment by atherdon** [comment] 2019-05-17 23:21
@ijb87 what do you think to do?

**Comment by atherdon** [comment] 2019-05-17 23:27
@ijb87 can you also give me your task number?

**Comment by ijb87** [comment] 2019-05-17 23:40
It's #240

**Comment by atherdon** [comment] 2019-05-23 10:19
We finished moving our methods, but didn't test it yet.

**Comment by Edebo** [comment] 2019-05-23 10:27
what is it to be done.task?

**Comment by atherdon** [comment] 2019-05-23 10:29
@Edebo when i'll move our changes to npm you'll be able to jump into https://github.com/GroceriStar/graphql-server/issues/145 give me 10 minutes

**Comment by atherdon** [comment] 2019-05-25 00:39
@vadim9999 looks like our moved functions work surprisingly well. without any mistakes(strange ;))
I didn't run graphql queries, so will keep this task open

**Comment by atherdon** [comment] 2019-05-30 19:52
closing it. if something will be broken - then re open it

**Closed by atherdon** 2019-05-30 19:52 UTC
Labels: enhancement, in-progress

**Comment by vadim9999** [comment] 2019-05-31 18:40
ok
