### ISSUE TITLE
convert ingredients ML dump into json file

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/sd#387] opened 2019-05-26 15:40 UTC
**Is your feature request related to a problem? Please describe.**
This task is based on https://github.com/GroceriStar/sd/issues/158#issuecomment-494670684

File is here: https://github.com/GroceriStar/sd/issues/158#issuecomment-493649858

i'm not sure right now how to connect @EbrahimKreem and @wahaj-47 but i think we'll figure it out during the work on it.

**Describe the solution you'd like**
I think it's a pretty obvious task - we need to use our generator script in order to create a new version of ingredients database with nutritional values together.
So i think this task will have 2 stages
- [x] save csv file inside of this repository(when everything will be done, we'll need to delete it)
- [x] parse data that we have inside of our csv file
- [x] create a json version(create a separated method for it, because later we might change some structure of this data, i.e extend it or merge with other files)
- [x] push this release to npm
- [ ] delete csv file when we'll have it's copy at json format

for sure, we need to have basic test for this file, we also need import/export from it. 
Good thing is - we'll be able to use it quite quickly at our graphql server.

**Additional context**
Parsing files is a default task for backend developers. nothing custom or complex at this moment

**Comment by EbrahimKreem** [comment] 2019-05-26 17:57
Hi @atherdon, As I understood from this task that we should parse JSON files inside CSV file

**Comment by EbrahimKreem** [comment] 2019-05-26 17:59
Am I correct or there is something missing

**Comment by wahaj-47** [comment] 2019-05-26 19:16
Is it just me, that when I download this file it just hangs my computer ?

**Comment by atherdon** [comment] 2019-05-26 19:52
> Hi @atherdon, As I understood from this task that we should parse JSON files inside CSV file

No, actually right now we moving data from CSV to JSON. Reason is - json format is widely used and it's much easy to import data to database. actually - as our database will increase it's complexity by itterations - we'll need to import data from time to time. so this is a good way to do it in a long distance.



> Is it just me, that when I download this file it just hangs my computer ?

I can download that file. But yeah, it's huge - it have a database that was scraped from EU food archive and have few thousands of rows. I see a few times glitches at Github recently - maybe it's a case.

**Comment by EbrahimKreem** [comment] 2019-05-26 20:18
ok, now what should I do?

**Comment by atherdon** [comment] 2019-05-26 20:22
First of all you need to define with Wahaj who will lead and how you'll separate work.
next task is to parse csv file. we can split it into few stages as well

**Comment by atherdon** [comment] 2019-05-26 20:28
for me this task is not only for making things done, but also about team building and having a discussion together.

**Comment by wahaj-47** [comment] 2019-05-26 23:22
I suggested using a parser module. Let’s start with choosing the right one. https://github.com/GroceriStar/sd/issues/158#issuecomment-494670684

**Comment by atherdon** [comment] 2019-05-27 07:05
> I suggested using a parser module. Let’s start with choosing the right one. [#158 (comment)](https://github.com/GroceriStar/sd/issues/158#issuecomment-494670684)

Yes, lets grab a first one, install it to npm, create a separated file for working with it, import module, import file, write some code, add path to that script at pkg.json

**Comment by EbrahimKreem** [comment] 2019-05-27 11:45
I think that https://www.npmjs.com/package/csv-parser is easy to use and they have a lot of examples but the problem is I tried this module with our CSV file and it gave me empty values then when I tried it with another CSV file it works correctly

**Comment by EbrahimKreem** [comment] 2019-05-27 11:47
with our csv file
![Screenshot from 2019-05-27 14-46-30](https://user-images.githubusercontent.com/32773511/58417708-5ddd3400-808e-11e9-8d38-3f961bbbe3a7.png)

**Comment by EbrahimKreem** [comment] 2019-05-27 11:48
with another csv file

![Screenshot from 2019-05-27 14-47-06](https://user-images.githubusercontent.com/32773511/58417751-7cdbc600-808e-11e9-9758-ef2285a4eed6.png)

**Comment by wahaj-47** [comment] 2019-05-27 12:01
I think that’s because our csv is laid out differently

**Comment by EbrahimKreem** [comment] 2019-05-27 13:35
I think that's because of the two lines in the beginning when I remove them I receive data
![Screenshot from 2019-05-27 16-34-52](https://user-images.githubusercontent.com/32773511/58423293-638e4600-809d-11e9-9f14-823a00d9d160.png)

**Comment by atherdon** [comment] 2019-05-27 13:44
we have that line because we convert from Excel to csv without removing a first line, aka title.
@wahaj-47 will you be able to download Excel file, remove first line and re-export csv file to this repo?

**Comment by atherdon** [comment] 2019-05-27 13:51
@EbrahimKreem can you also open PR with your current changes? it's hard for me without looking at code

**Comment by EbrahimKreem** [comment] 2019-05-27 14:00
ok

**Comment by wahaj-47** [comment] 2019-05-27 14:26
On it

**Comment by atherdon** [comment] 2019-05-27 14:46
Ok, as I merge latest changes from Ebrahim I think he is leading and me with Wahaj will work on "cleaning up"

**Comment by atherdon** [comment] 2019-05-27 16:39
@wahaj-47 next step for you will be moving this script into generator folder, then we need to add tests for this file and script and i think we can start to code method that will adjust/save into json our data.
by adjust - let's have a simple example - add to each row an autogenerated id. because we always need ids

**Comment by atherdon** [comment] 2019-05-27 16:47
can someone tell me the list of fields that each row has?

**Comment by EbrahimKreem** [comment] 2019-05-27 16:51
do you mean the headers?

**Comment by EbrahimKreem** [comment] 2019-05-27 16:53
but when I look to the file it is not organized

**Comment by atherdon** [comment] 2019-05-27 16:54
yep, headers/columns.
i just want a quick/preliminary list - lazy to open it myself :)

**Comment by EbrahimKreem** [comment] 2019-05-27 16:57
Food class level | Metrics | Concentration levels | Country

**Comment by atherdon** [comment] 2019-05-27 17:01
emm, what about measurements? is it metrics?

**Comment by wahaj-47** [comment] 2019-05-27 19:36
> @wahaj-47 next step for you will be moving this script into generator folder, then we need to add tests for this file and script and i think we can start to code method that will adjust/save into json our data.
> by adjust - let's have a simple example - add to each row an autogenerated id. because we always need ids

Aren't we supposed to be generating a JSON file ?

**Comment by atherdon** [comment] 2019-05-27 19:41
@wahaj-47 first of all - we need to complete this part: https://github.com/GroceriStar/sd/issues/387#issuecomment-496217769

**Comment by wahaj-47** [comment] 2019-05-27 19:43
> @wahaj-47 first of all - we need to complete this part: [#387 (comment)](https://github.com/GroceriStar/sd/issues/387#issuecomment-496217769)

That's complete. I didn't do it but its already done. Thanks @EbrahimKreem

**Comment by atherdon** [comment] 2019-05-27 19:54
ohh, i just don't know about it. so the newest version is uploaded at this repo and parsing stuff works well, right?

**Comment by atherdon** [comment] 2019-05-27 19:55
Yes, we'll generate a json. but script, that Ebrahim wrote, located in `data` folder with is not ideal way for our structure

**Comment by atherdon** [comment] 2019-05-27 19:55
> we just use this csv parser module once to generate the JSON and get rid of it ?
And then in generator create a method to adjust that JSON .

totally correct

**Comment by wahaj-47** [comment] 2019-05-28 13:52
> Yes, we'll generate a json. but script, that Ebrahim wrote, located in `data` folder with is not ideal way for our structure

I don't quite understand what is going on in the csv. As @EbrahimKreem  said, the file is not properly organized.

**Comment by EbrahimKreem** [comment] 2019-05-28 14:03
this file cannot be parsed

**Comment by EbrahimKreem** [comment] 2019-05-28 14:04
It has duplicate headers and it doesn't follow CSV file conventions

**Comment by atherdon** [comment] 2019-05-28 14:19
maybe it's a problem at parser module that we picked?
did you saw an Excel version of this file before?

>

**Comment by EbrahimKreem** [comment] 2019-05-28 14:51
:sweat_smile: I don't have Excel program on my computer because I'm running Ubuntu ... so do you think if we change the parser module we will solve the problem?

**Comment by atherdon** [comment] 2019-05-28 15:02
1. you can use libreoffice or upload Excel file into google docs(better and
easiest option)
2. i'm convinced that this file can be parced, we just need to find a way
how to do it. as you see at that comment - i proposed different parsers -
just in case if things will go wrong.

**Comment by wahaj-47** [comment] 2019-05-28 16:04
Yes I’ve viewed the file on excel and yes it has duplicate headers and there are cells which are supposedly headers but are not. 
Maybe we can skip a few lines and generate a JSON and then adjust it so as to match the csv.

**Comment by atherdon** [comment] 2019-05-28 16:08
can you show me what do you mean on screenshots?

**Comment by atherdon** [comment] 2019-05-28 18:53
while we thinking - let's move script into generator folder. and if someone has new code changes - open a pr with your changes please

**Comment by wahaj-47** [comment] 2019-05-29 11:25
#403 
Alright, I have moved the script to generator/project/Foodcomposition directory and I have managed to generate a JSON but only for the country: Finland. I was thinking maybe we can generate multiple JSONs for each country and merge them together.
Right now the generated JSON has the following structure
{
    "Food class": "",
    "Food (FoodEx2 description)": "Fries (finger chips)",
    "Microgram/100 gram": "0.6",
    "Milligram/100 gram": "584.7818"
  },
We have to add a country key to each object right now, but if we have separate JSONs for each country, then this task will be easy and then we can merge to create a single JSON.

**Comment by atherdon** [comment] 2019-05-29 12:45
> maybe we can generate multiple JSONs for each country

yes, let's try this way @EbrahimKreem what do you think? 
Maybe we'll also find that country - that have a "bad" data

I remember how my team and I was importing 10-year-old/custom data into the new clean database - I was forced to sleep by 15 minutes, in order to upload a next chank that our server was able to digest 




> "Food class": "",
> "Food (FoodEx2 description)": "Fries (finger chips)",
> "Microgram/100 gram": "0.6",
> "Milligram/100 gram": "584.7818"

I have feeling that we have a more long number of element there. or I'm mistaken?

**Comment by EbrahimKreem** [comment] 2019-05-29 13:57
> I have feeling that we have a more long number of element there. or I'm mistaken?

yeah I agree with as I understand from the file we have a lot of headers
Food (FoodEx2 description) | Metrics | Concentration levels | Microgram/100 gram | Milligram/100 gram

**Comment by EbrahimKreem** [comment] 2019-05-29 14:00
Is there any tool to reorganize the CSV file?

**Comment by atherdon** [comment] 2019-05-29 14:01
it's like this structure, right?:
country
 -- food ingredient
 ---- Food (FoodEx2 description)
 ---- Metrics 
 ---- Concentration levels  
 ---- Microgram/100 gram
 ---- Milligram/100 gram

---

I think when it will be imported to json we'll also merge this data with measurements data tables, that was created by Wahaj previously, so clean/easy to understand code will help up to make it work and connect with measurements easily

**Comment by atherdon** [comment] 2019-05-29 14:04
i don't think that any tool will actually really help us.
because data is custom, created/merged from 2 different sources of our
maching learning intern from France.
so i think we need to create that tool by our hands :)

actually - it's just a big array of arrays for me. so i think loops is
our best bet here.
Btw, maybe, just maybe - lodash as module that have wrappers around default
loops will help us to reduce code complexity

>

**Comment by atherdon** [comment] 2019-05-29 16:05
I think we also need to createa separated file aka foodcompositionFiles.js and be able to export all files from this module. it's not very important right now, but by doing this - we'll be able to connect that data with our servers and try to use them in short amount of time

**Comment by atherdon** [comment] 2019-05-30 16:04
please keep me posted what we're doing here - maybe i can help somehow

**Comment by EbrahimKreem** [comment] 2019-06-01 13:52
Now the eight generated JSON files have the same output except the country field so if I generate one file and randomly generate the country field would it be good or just keep it as it is

**Comment by atherdon** [comment] 2019-06-01 13:55
show me a screenshot, having very lazy brain today. 
more details please. or show code at PR...

**Comment by EbrahimKreem** [comment] 2019-06-01 14:03
ok, now there are eight JSON files that @wahaj-47 generated from Food_Composition there are identical except the country field

![Screenshot from 2019-06-01 16-59-44](https://user-images.githubusercontent.com/32773511/58749433-be091700-848e-11e9-8f3c-27f3f9888d58.png)

![Screenshot from 2019-06-01 16-59-59](https://user-images.githubusercontent.com/32773511/58749449-0e807480-848f-11e9-8631-521ba84cfa2e.png)

**Comment by EbrahimKreem** [comment] 2019-06-01 14:03
so I think it is useful to have one file and generate the country field randomly

**Comment by atherdon** [comment] 2019-06-01 14:05
now i got it. i like this plan. it will reduce duplicates. you'll adjust Wahaj code for it, right? i mean there no needs to recreate it from scratch

**Comment by EbrahimKreem** [comment] 2019-06-01 14:06
yes

**Comment by atherdon** [comment] 2019-06-01 14:06
good. do it. and promise you'll be surprised soon :)

**Comment by EbrahimKreem** [comment] 2019-06-01 15:19
> ok, lets think how to fix some codeclimte issues

what is codeclimte?

**Comment by atherdon** [comment] 2019-06-01 15:23
it's a cool too that will maybe make our life harder - but code will be better :)

**Comment by wahaj-47** [comment] 2019-06-01 20:36
They’re are not identical. 
The keys are identical but their values are what’s in the spreadsheet. The values are specific to each country. Each file has data specific to that country.

**Comment by atherdon** [comment] 2019-06-02 17:30
@EbrahimKreem as values are not identical - then we cannot do what you proposed. What will be our next step @wahaj-47 do we need to roll back some changes or adjust the latest changes that were made there?

**Comment by wahaj-47** [comment] 2019-06-02 20:38
Right now, I think we just need to loop over these arrays in JSONs and add the required keys, so that the JSONs match the csv completely.

**Comment by atherdon** [comment] 2019-06-02 21:16
ok, do it - but @EbrahimKreem deleted files that were created before

**Comment by wahaj-47** [comment] 2019-06-02 22:59
No problem, I think it’ll be better to add the looping logic to the current script (hope that’s still intact)

**Comment by atherdon** [comment] 2019-06-02 23:21
i'm not sure - please check the latest changes that were made

**Comment by atherdon** [comment] 2019-06-03 11:58
@wahaj-47 what will be our next steps here?

**Comment by wahaj-47** [comment] 2019-06-03 12:01
I’ve parsed the csv into a single JSON. I think all we need to do is to verify that all the fields from the csv have been moved to JSON.

**Comment by atherdon** [comment] 2019-06-03 12:02
Can you also check #450 PR becausei don;t want to lose work that @EbrahimKreem did few days ago

**Comment by wahaj-47** [comment] 2019-06-03 12:12
There wasn’t really a way to parse our csv as a whole, so what I did was create separate csv for each country containing data specific to that country. Then parse each csv separately and merge the returned JSONs into one. What @EbraheemKreem is trying to do is to parse the csv as a whole. I think it’ll be better to wait for his thoughts on this.

**Comment by atherdon** [comment] 2019-06-03 12:19
Ok, will wait for him. maybe you can go through his commits and see what can be useful for us in next stages?

**Comment by wahaj-47** [comment] 2019-06-03 12:27
Already did. I think we both have done pretty much the same stuff except he’s assigning random country to each object.

**Comment by atherdon** [comment] 2019-06-03 12:30
let's think about this: 
one of our associates grab the latest database - csv format from US Food database. can code from that PR will be used for that case as well?

**Comment by wahaj-47** [comment] 2019-06-03 12:36
Yes and no 
The looping logic is sloppy. 
If that can be improved then yes.

**Comment by atherdon** [comment] 2019-06-03 12:39
ok, then let's do some small work that necessary.
Can you connect our json generated files at index.js file, so we can use that files outside of out module?

**Comment by atherdon** [comment] 2019-06-03 12:43
can you also point me to the json files that we generated. because right now it's a bit confusing.
at src/data we have csv files. at output folder we don't have files and ... not very clear right now

**Comment by EbrahimKreem** [comment] 2019-06-03 13:28
did you make a PR for your latest changes @wahaj-47?

**Comment by atherdon** [comment] 2019-06-03 13:30
@EbrahimKreem check #469

**Comment by wahaj-47** [comment] 2019-06-03 13:34
@EbrahimKreem my changes have been merged. 
@atherdon because the generated file is at https://github.com/wahaj-47/sd/blob/master/generator/projects/FoodComposition/FoodComposition.json

**Comment by EbrahimKreem** [comment] 2019-06-03 13:59
#450

**Comment by EbrahimKreem** [comment] 2019-06-03 14:00
#450

**Comment by atherdon** [comment] 2019-06-03 14:54
@EbrahimKreem 

> then we need to add tests for this file and script and i think we can start to code method that will adjust/save into json our data.
> by adjust - let's have a simple example - add to each row an autogenerated id. because we always need ids



> I think we also need to createa separated file aka foodcompositionFiles.js and be able to export all files from this module. it's not very important right now, but by doing this - we'll be able to connect that data with our servers and try to use them in short amount of time


> Can you connect our json generated files at index.js file, so we can use that files outside of out module?


i think this was not done yet
And #412

**Comment by wahaj-47** [comment] 2019-06-03 14:58
I think we need to improve the script if we want to use it off the shelf for other csv. 
https://github.com/GroceriStar/sd/issues/387#issuecomment-498238340

**Comment by atherdon** [comment] 2019-06-03 15:04
Ok, just decide together what both of you will do in order to don't have a lot of intersections

**Comment by wahaj-47** [comment] 2019-06-03 15:07
Can we presume that every time a new csv filed comes through the formatting of the csv will be the same ?

**Comment by atherdon** [comment] 2019-06-15 19:18
@EbrahimKreem tell me if you want to jump into development of our graphql server

**Comment by atherdon** [comment] 2019-06-21 05:23
@vadim9999 I think this task is partially done, and we need to figure out what is left to do

**Comment by vadim9999** [comment] 2019-06-21 17:15
@atherdon 
>create a json version(create a separated method for it, because later we might change some structure of this data, i.e extend it or merge with other files)

Can't find json version

**Comment by atherdon** [comment] 2019-06-21 17:33
yep it's a bit mess up
- https://github.com/GroceriStar/sd/tree/master/generator/projects/FoodComposition
- https://github.com/GroceriStar/sd/tree/master/src/data/FoodComposition

please try to run a csv parser script - i assume it will break, because we updated some of methods

**Comment by atherdon** [comment] 2019-06-21 17:50
you can also add to readme an explanation about how to run stuff for Foodcomposition.
because when we'll move generator out - it will be important to test and re-run all scripts again

**Comment by vadim9999** [comment] 2019-06-21 19:46
> yep it's a bit mess up
> 
> * https://github.com/GroceriStar/sd/tree/master/generator/projects/FoodComposition
> * https://github.com/GroceriStar/sd/tree/master/src/data/FoodComposition
> 
> please try to run a csv parser script - i assume it will break, because we updated some of methods

I have run it and it's working

**Comment by vadim9999** [comment] 2019-06-21 19:50
in csv_parser.js I can't find method that creates json version. Maybe this step is not done or the method is moved in another place. What format of data should contain this json?

**Comment by atherdon** [comment] 2019-06-21 20:17
it should be just split by countries.
i think we have some long script for parser.
any way - you can grab this task and finish it

>

**Comment by vadim9999** [comment] 2019-06-22 12:59
> create a json version(create a separated method for it, because later we might change some structure of this data, i.e extend it or merge with other files)

It's not done. Because it's not split by countries just one file FoodComposition.json that contains many countries. Should I complete it or leave interns?

**Comment by atherdon** [comment] 2019-06-22 13:06
but did you saw a separated csv files that we have at data folder, right?

And you can also check out some folders, under USFA project - it contains
also a few files - so by looking at code, you might find out how we did it.
or we can grab an @Edebo here and he can explain some details to us here

I'm ok if you complete it - we just need to do in a smart way - by using
code that is actually done. when we'll complete it - we'll actually be able
to put our hands into backend of this system, because it's a huge amount of
data, more than we play with you before.

>

**Comment by vadim9999** [comment] 2019-06-22 13:13
Yes, in data FoodComposition are:
```
├── Food_Composition.csv
├── Food_Composition - Finland.csv
├── Food_Composition - France.csv
├── Food_Composition - Germany.csv
├── Food_Composition - Italy.csv
├── Food_Composition - Netherlands.csv
├── Food_Composition - Sweden.csv
├── Food_Composition - United Kingdom.csv
└── Readme.md

```
but in folder FoodComposition of generator is one json file FoodComposition.json.
Ok, we can give to complete task @Edebo

**Comment by atherdon** [comment] 2019-06-22 13:37
ok, then let's think what you can also do.
tell me what do you want to do :)

>

**Comment by vadim9999** [comment] 2019-06-22 13:44
Then I will complete it

**Comment by atherdon** [comment] 2019-06-22 13:53
go forward with it

>

**Comment by atherdon** [comment] 2019-06-22 16:26
Ok, i think we can close this task. I moved all necessary things to another task - this thread became very long

**Comment by atherdon** [comment] 2019-06-22 16:28
@vadim9999 please also push a new release(minor) to npm

**Comment by vadim9999** [comment] 2019-06-22 16:40
Done

**Comment by atherdon** [comment] 2019-06-22 16:42
closing it. pretty happy about it

**Comment by vadim9999** [comment] 2019-06-22 16:42
Should I replace csv by json in src/data?

**Closed** 2019-06-22 16:42 UTC
Labels: enhancement, generator, help wanted, in-progress

**Comment by atherdon** [comment] 2019-06-22 16:46
to be honest - not inportant at this moment. because with changes, tat i'm making at #565 we'll improve whole process.
